### ISSUE TITLE
Unable to resolve service for type 'AutoMapper.Configuration.IConfiguration' 

### ISSUE THREAD

**Issue by t-dark** [DarinHan/IdentityServer4.Dapper#2]
大神您好，请教两个问题，谢谢。
1：下载了直接运行提示：
System.InvalidOperationException:“Unable to resolve service for type 'AutoMapper.Configuration.IConfiguration' while attempting to activate 'IdentityServer.Dapper.Test.Startup'.”
然后更改了startup中的using如下：
//using AutoMapper.Configuration;
using Microsoft.Extensions.Configuration;
这样可以运行了，数据也入库了。
因为automapper我没用过，我简单看了下automapper的用法，您这个项目里的Mapper是静态类构造函数创建的映射。我不确定我这样改有没有问题？
2：我看了下ids4官方的示例，数据库还有角色表和用户表，貌似您这个里面没有。

**Comment by mingyangzhu** [comment]
这个应该是作者引入错误的命名空间导致的。替换下就可以了。你的做法是对的。

**Comment by t-dark** [comment]
> 这个应该是作者引入错误的命名空间导致的。替换下就可以了。你的做法是对的。

好的，谢谢。

**Comment by mingyangzhu** [comment]
支持 支持  。net core 生态将因为像你们这些大神日趋完善。
